Solved JS Assignments
CSOC-23/Week1-Web pull request #29
Opened 2023-06-11 00:09 UTC by Shriya-sinha

2023-06-22 09:29 UTC, BabyElias commented
The assignment is incomplete. Attempt all the tests and make a commit with atleast 140 score.

2023-06-23 11:57 UTC, EshaanAgg requested changes
Please make these changes.

2023-06-23 11:57 UTC, EshaanAgg commented on src/conditionalAndLoops.js
> +getFizzBuzz(15);
Remove or comment out these calls to functions. They interfere with the testing script.

2023-06-23 11:59 UTC, EshaanAgg commented on src/array.js
> +console.log(getArrayOfPositives([ 0, 1, 2, 3, 4, 5 ]));
Delete all these `console.log`s from all the test files as well. They can cause the test suite to break undetermistically, and clog up the testing window screen.

2023-06-24 17:06 UTC, vaibhav-1508 commented on src/conditionalAndLoops.js
> +function timespanToHumanString(startDate, endDate) {
test suite was unable to run cuz of the missing function

2023-06-24 17:07 UTC, closed without merging